version: '2.1'

services:
  mycookingbook:
    image: mycookingbook
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 9229:9229
    ## set your startup file here
    command: nodemon --inspect prod-server.js
